### PR TITLE
EntityPreloader: remove useless `@template`s

### LINKED ISSUE #23: Why is `EntityPreloader` generic?
I want to use `EntityPreloader` as a service: https://github.com/symfony/recipes-contrib/pull/1850

But when I use the service, I get a phpstan error:

> phpstan: Method App\Repository\FooRepository::__construct() has parameter $preloader with generic class ShipMonk\DoctrineEntityPreloader\EntityPreloader but does not specify its types: E

Does the `@template` make sense for `EntityPreloader`? An `EntityPreloader` instance seems not to be bound to a specific entity, as you can see in the readme, where the same preloader instance is used to load relations of different entities (categories and articles): https://github.com/shipmonk-rnd/doctrine-entity-preloader/tree/master#usage

### PR DESCRIPTION
**Pull request by janedbal**
Closes #23

### CODE REVIEW

File: src/EntityPreloader.php [hunk 1]
```diff
@@ -97,7 +90,7 @@ private function getCommonAncestor(array $entities): ?string
             }
 
             while (!is_a($entityClassName, $commonAncestor, true)) {
-                /** @var class-string<S>|false $commonAncestor */
+                /** @var class-string|false $commonAncestor */
```
Comment (JanTvrdik) [inline src/EntityPreloader.php:93]: This may not need the `@var` at all now

**Comment by gharlan** [comment]
Thanks for the quick fix, and thanks for the nice lib!
